version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      aspire-hosting:
        patterns:
          - "Aspire.Hosting.*"
      open-telemetry:
        patterns:
          - "OpenTelemetry"
          - "OpenTelemetry.*"
      microsoft-aspnetcore:
        patterns:
          - "Microsoft.AspNetCore"
          - "Microsoft.AspNetCore.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
