<Project>
  <!-- General-->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>

  <!-- Support solution level pack/publish -->
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
  </PropertyGroup>


  <!-- Package / Source link-->
  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>Alex Crome</Authors>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <DebugType>embedded</DebugType>
  </PropertyGroup>



</Project>
