<Project>
  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>Alex Crome</Authors>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
  </PropertyGroup>
</Project>
